# Generated by Django 5.2.6 on 2025-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_github_avatar_url_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
