# Generated by Django 5.2.6 on 2025-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_synced_github_followers_following',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
