# Generated by Django 5.2.6 on 2025-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_synced_github_followers_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
