# Generated by Django 5.2.6 on 2025-12-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_account_type_user_bio_user_blog_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intelligent_follow_enabled',
            field=models.BooleanField(default=False, help_text='Enable intelligent follow/unfollow to boost followers'),
        ),
        migrations.AddField(
            model_name='user',
            name='intelligent_follow_schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual Only')], default='manual', help_text='How often to run intelligent follow/unfollow', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_intelligent_follow',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
