# Generated by Django 4.2.28 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_intelligent_follow_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_intelligent_follow',
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(choices=[('collaborate', 'Open to Collaborate'), ('hiring', 'Hiring / Looking for Talent'), ('job', 'Looking for Opportunities'), ('learning', 'Learning New Things'), ('none', 'Not Specified')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
