# Generated by Django 4.2.28 on 2026-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_last_intelligent_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_intelligent_follow',
            field=models.DateTimeField(blank=True, help_text='Last time the intelligent follow cycle was run', null=True),
        ),
    ]
