# Generated by Django 5.2.6 on 2025-10-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('is_fetching', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='github_mana_slug_8a691f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('contributions_last_year', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('profile_url', models.URLField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='github_management.country')),
            ],
            options={
                'verbose_name': 'GitHub User',
                'verbose_name_plural': 'GitHub Users',
                'ordering': ['-contributions_last_year'],
                'indexes': [models.Index(fields=['country'], name='github_mana_country_c4039b_idx'), models.Index(fields=['contributions_last_year'], name='github_mana_contrib_37814d_idx'), models.Index(fields=['rank'], name='github_mana_rank_65d3d9_idx')],
            },
        ),
    ]
