# Generated by Django 5.2.6 on 2025-10-09 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubFollowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('followed_back', 'Followed Back'), ('not_followed_back', 'Not Followed Back')], default='pending', max_length=20)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('followed_back_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_actions', to='github_management.githubuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_follow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['status'], name='github_mana_status_e8e247_idx'), models.Index(fields=['followed_at'], name='github_mana_followe_518296_idx'), models.Index(fields=['user', 'status'], name='github_mana_user_id_b64e5d_idx')],
                'unique_together': {('user', 'github_user')},
            },
        ),
    ]
