# Generated by Django 5.2.6 on 2025-10-15 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0002_githubfollowaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubuser',
            options={'verbose_name': 'GitHub User', 'verbose_name_plural': 'GitHub Users'},
        ),
        migrations.RemoveIndex(
            model_name='githubuser',
            name='github_mana_contrib_37814d_idx',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='profile_url',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='username',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
    ]
