# Generated by Django 5.2.6 on 2025-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0003_alter_githubuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
