# Generated by Django 5.2.6 on 2025-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0004_githubuser_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
