# Generated by Django 5.2.6 on 2025-11-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0006_githubuser_account_type_githubuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='intelligence_score',
            field=models.FloatField(default=0),
        ),
    ]
