# Generated by Django 4.2.28 on 2026-02-09 08:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0007_githubuser_intelligence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(db_index=True, max_length=100)),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('skill_category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('library', 'Library'), ('tool', 'Tool'), ('platform', 'Platform'), ('database', 'Database'), ('other', 'Other')], default='other', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('proficiency_score', models.FloatField(default=0.0)),
                ('repo_count', models.PositiveIntegerField(default=0)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('lines_of_code', models.PositiveIntegerField(default=0)),
                ('first_used', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Developer Skill',
                'verbose_name_plural': 'Developer Skills',
                'ordering': ['-proficiency_score', '-total_stars'],
            },
        ),
        migrations.CreateModel(
            name='GitHubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('PushEvent', 'Push'), ('CreateEvent', 'Create'), ('DeleteEvent', 'Delete'), ('ForkEvent', 'Fork'), ('WatchEvent', 'Star'), ('PullRequestEvent', 'Pull Request'), ('PullRequestReviewEvent', 'PR Review'), ('PullRequestReviewCommentEvent', 'PR Review Comment'), ('IssuesEvent', 'Issue'), ('IssueCommentEvent', 'Issue Comment'), ('CommitCommentEvent', 'Commit Comment'), ('ReleaseEvent', 'Release'), ('MemberEvent', 'Member'), ('PublicEvent', 'Made Public'), ('GollumEvent', 'Wiki'), ('SponsorshipEvent', 'Sponsorship')], db_index=True, max_length=50)),
                ('actor_username', models.CharField(db_index=True, max_length=100)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('repo_name', models.CharField(db_index=True, max_length=512)),
                ('repo_id', models.BigIntegerField(blank=True, null=True)),
                ('org_login', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('org_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('github_created_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GitHub Event',
                'verbose_name_plural': 'GitHub Events',
                'ordering': ['-github_created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(db_index=True, unique=True)),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('login', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=100, null=True)),
                ('html_url', models.URLField(max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('org_type', models.CharField(default='Organization', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('public_gists', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('has_organization_projects', models.BooleanField(default=True)),
                ('has_repository_projects', models.BooleanField(default=True)),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GitHub Organization',
                'verbose_name_plural': 'GitHub Organizations',
                'ordering': ['-public_repos', '-followers'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(db_index=True, unique=True)),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(db_index=True, max_length=512, unique=True)),
                ('owner_username', models.CharField(db_index=True, max_length=100)),
                ('owner_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, max_length=500, null=True)),
                ('html_url', models.URLField(max_length=500)),
                ('repo_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('fork', 'Fork')], default='public', max_length=10)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('stargazers_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('watchers_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('open_issues_count', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=0)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('github_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_spdx_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('has_issues', models.BooleanField(default=True)),
                ('has_projects', models.BooleanField(default=True)),
                ('has_downloads', models.BooleanField(default=True)),
                ('has_wiki', models.BooleanField(default=True)),
                ('has_pages', models.BooleanField(default=False)),
                ('has_discussions', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-stargazers_count', '-forks_count'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('global', 'Global'), ('country', 'By Country'), ('language', 'By Language'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('followers', 'Most Followers'), ('contributions', 'Most Contributions'), ('repositories', 'Most Repositories'), ('intelligence', 'Intelligence Score')], db_index=True, max_length=20)),
                ('country_slug', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('rankings', models.JSONField(default=list)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_stale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(db_index=True, max_length=100)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('score', models.FloatField()),
                ('display_data', models.JSONField(default=dict)),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='github_management.leaderboard')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', '-last_updated'], name='github_mana_leaderb_42758c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['country_slug', 'leaderboard_type'], name='github_mana_country_fa6288_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['language', 'leaderboard_type'], name='github_mana_languag_b5daf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('leaderboard_type', 'country_slug', 'language', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['owner_username'], name='github_mana_owner_u_6d59f0_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['language'], name='github_mana_languag_5222fb_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['-stargazers_count'], name='github_mana_stargaz_c0f8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['-github_updated_at'], name='github_mana_github__ade527_idx'),
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['is_fork', '-stargazers_count'], name='github_mana_is_fork_5af6da_idx'),
        ),
        migrations.AddIndex(
            model_name='githuborganization',
            index=models.Index(fields=['login'], name='github_mana_login_56f239_idx'),
        ),
        migrations.AddIndex(
            model_name='githuborganization',
            index=models.Index(fields=['-public_repos'], name='github_mana_public__1fac55_idx'),
        ),
        migrations.AddIndex(
            model_name='githuborganization',
            index=models.Index(fields=['-followers'], name='github_mana_followe_1353d7_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['actor_username', '-github_created_at'], name='github_mana_actor_u_c399b9_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['repo_name', '-github_created_at'], name='github_mana_repo_na_c7968f_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['event_type', '-github_created_at'], name='github_mana_event_t_85676d_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['-github_created_at'], name='github_mana_github__ce925c_idx'),
        ),
        migrations.AddIndex(
            model_name='developerskill',
            index=models.Index(fields=['github_username', '-proficiency_score'], name='github_mana_github__ff5682_idx'),
        ),
        migrations.AddIndex(
            model_name='developerskill',
            index=models.Index(fields=['skill_name', '-proficiency_score'], name='github_mana_skill_n_bd8668_idx'),
        ),
        migrations.AddIndex(
            model_name='developerskill',
            index=models.Index(fields=['skill_category', '-proficiency_score'], name='github_mana_skill_c_0c1a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='developerskill',
            unique_together={('github_username', 'skill_name')},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', 'rank'], name='github_mana_leaderb_60d1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['github_username', '-updated_at'], name='github_mana_github__a94f07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('leaderboard', 'github_username')},
        ),
    ]
