# Generated by Django 4.2.28 on 2026-02-09 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0008_developerskill_githubevent_githuborganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('public_repos_count', models.PositiveIntegerField(default=0)),
                ('contributions_count', models.PositiveIntegerField(default=0)),
                ('stars_received_count', models.PositiveIntegerField(default=0)),
                ('followers_delta', models.IntegerField(default=0)),
                ('stars_delta', models.IntegerField(default=0)),
                ('contributions_delta', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Growth Analytics',
                'verbose_name_plural': 'Growth Analytics Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['github_username', '-date'], name='github_mana_github__267e0a_idx')],
                'unique_together': {('github_username', 'date')},
            },
        ),
    ]
