# Generated by Django 4.2.28 on 2026-02-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_management', '0009_growthanalytics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='githubfollowaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='githubfollowaction',
            name='action_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow')], default='follow', max_length=10),
        ),
        migrations.AddField(
            model_name='githubfollowaction',
            name='target_username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubfollowaction',
            name='github_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_actions', to='github_management.githubuser'),
        ),
        migrations.AddIndex(
            model_name='githubfollowaction',
            index=models.Index(fields=['action_type'], name='github_mana_action__77448f_idx'),
        ),
        migrations.AddIndex(
            model_name='githubfollowaction',
            index=models.Index(fields=['target_username'], name='github_mana_target__3964a3_idx'),
        ),
    ]
