"""
Django settings for github_management_project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
from pathlib import Path
from datetime import timedelta
import django.utils.translation
from django.dispatch import Signal
from dotenv import load_dotenv

# Load environment variables from .env file (for local/dev)
load_dotenv()

# -----------------------------
# Base Directory
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------
# Backward Compatibility Fixes
# -----------------------------
if not hasattr(django.utils.translation, 'ugettext'):
    django.utils.translation.ugettext = django.utils.translation.gettext
if not hasattr(django.utils.translation, 'ugettext_lazy'):
    django.utils.translation.ugettext_lazy = django.utils.translation.gettext_lazy

if 'providing_args' not in Signal.__init__.__code__.co_varnames:
    _old_init = Signal.__init__

    def _new_init(self, providing_args=None, *args, **kwargs):
        _old_init(self, *args, **kwargs)

    Signal.__init__ = _new_init


# -----------------------------
# Security & Debug Settings
# -----------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# CSRF_TRUSTED_ORIGINS = os.getenv(
#     "DJANGO_CSRF_TRUSTED_ORIGINS",
#     "https://example.com"
# ).split(",")

CORS_ALLOWED_ORIGINS = os.getenv(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,https://github.example.com,https://example.com"
).split(",")

CORS_ALLOW_CREDENTIALS = True


# -----------------------------
# Installed Applications
# -----------------------------
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'django.contrib.humanize',
    'django.contrib.sitemaps',

    # Third-party apps
    'graphene_django',
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    'graphql_auth',
    'django_filters',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',

    # Local apps
    'github_management',
    'django_celery_beat',
    'users',
    # 'discussions',
    'badges',
]


# -----------------------------
# Middleware
# -----------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


# -----------------------------
# User & Authentication
# -----------------------------
AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

GRAPHQL_JWT = {
    "JWT_EXPIRATION_DELTA": timedelta(days=1),
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=7),
}


# -----------------------------
# Allauth Configuration
# -----------------------------
SITE_ID = int(os.getenv("DJANGO_SITE_ID", 1))
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = os.getenv("ACCOUNT_EMAIL_VERIFICATION", "none")
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'password1', 'password2']

ACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSignupForm',
}

SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True

LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
# Comma-separated list of tokens for rotation
GITHUB_TOKENS_STR = os.getenv("GITHUB_TOKENS", "")
GITHUB_TOKENS = [t.strip() for t in GITHUB_TOKENS_STR.split(",") if t.strip()]
if GITHUB_TOKEN and GITHUB_TOKEN not in GITHUB_TOKENS:
    GITHUB_TOKENS.append(GITHUB_TOKEN)
# -----------------------------
# OAuth Settings (GitHub + Google)
# -----------------------------
GITHUB_OAUTH2_CLIENT_ID = os.getenv("GITHUB_OAUTH2_CLIENT_ID")
GITHUB_OAUTH2_SECRET = os.getenv("GITHUB_OAUTH2_SECRET")
GOOGLE_OAUTH2_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_SECRET = os.getenv("GOOGLE_OAUTH2_SECRET")

# -----------------------------
# SiteWise Customer Support
# -----------------------------
SITEWISE_API_KEY = os.getenv("SITEWISE_API_KEY", "")
SITEWISE_BASE_URL = os.getenv("SITEWISE_BASE_URL", "https://api.yoursitewise.com")

# Social Account Settings
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': ['user', 'repo', 'read:org'],
        'APP': {
            'client_id': GITHUB_OAUTH2_CLIENT_ID,
            'secret': GITHUB_OAUTH2_SECRET,
            'key': ''
        },
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'openid',
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
        'APP': {
            'client_id': GOOGLE_OAUTH2_CLIENT_ID,
            'secret': GOOGLE_OAUTH2_SECRET,
            'key': ''
        }
    }
}

# Auth settings
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# AllAuth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_STORE_TOKENS = True
if not DEBUG:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = os.getenv("ACCOUNT_DEFAULT_HTTP_PROTOCOL", "https")

    # # Session settings
    SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", 1209600))  # 2 weeks in seconds
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True").lower() == "true"
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True").lower() == "true"
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Explicitly disable these for local development to avoid issues
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False


# -----------------------------
# Database Configuration
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        'NAME': os.getenv("DB_NAME", "github"),
        'USER': os.getenv("DB_USER", "example"),
        'PASSWORD': os.getenv("DB_PASSWORD", "123456"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}


# -----------------------------
# Celery Configuration
# -----------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", "UTC")

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'daily-country-sync': {
        'task': 'github_management.tasks.daily_country_sync_task',
        'schedule': crontab(hour=0, minute=0),  # Run daily at midnight
    },
    'refresh-leaderboards': {
        'task': 'github_management.tasks.update_all_leaderboards_task',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'global-stats-sync': {
        'task': 'github_management.tasks.periodic_sync_dispatcher',
        'schedule': crontab(minute=0),  # Run every hour
    },
    'intelligent-follow-scheduler': {
        'task': 'users.tasks.intelligent_follow_scheduler',
        'schedule': crontab(hour='*/3', minute=0),  # Run every 3 hours
    },
    'cleanup-follow-actions': {
        'task': 'users.tasks.cleanup_old_follow_actions',
        'schedule': crontab(hour=3, minute=0),  # Run daily at 3 AM
    },
}


# -----------------------------
# Templates
# -----------------------------
ROOT_URLCONF = 'github_management_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.google_auth',
                'github_management_project.utils.sitewise_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'github_management_project.wsgi.application'


# -----------------------------
# Password Validators
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -----------------------------
# Internationalization
# -----------------------------
LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "en-us")
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Africa/Dar_es_Salaam")
USE_I18N = True
USE_TZ = True


# -----------------------------
# Static & Media Files
# -----------------------------
STATIC_URL = '/static/'
# STATIC_ROOT = os.getenv("DJANGO_STATIC_ROOT", os.path.join(BASE_DIR, "static"))
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))


# -----------------------------
# Default Auto Field
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
