# Generated by Django 5.1.7 on 2025-06-18 08:18

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of chickens this house can hold')),
                ('current_chicken_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EggInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eggs', models.PositiveIntegerField(default=0)),
                ('rejected_eggs', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(help_text='e.g., ml, tablets, kg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_MANAGER', 'Stock Manager'), ('WORKER', 'Worker'), ('DOCTOR', 'Doctor')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                # ('chicken_house', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poutryapp.chickenhouse')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChickenDeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('number_dead', models.PositiveIntegerField()),
                ('doctor_notes', models.TextField(blank=True)),
                ('possible_cause', models.CharField(blank=True, max_length=100)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_deaths', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_deaths', to=settings.AUTH_USER_MODEL)),
                ('chicken_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.chickenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('full_trays', models.PositiveIntegerField(help_text='Number of full trays (30 eggs per tray)')),
                ('loose_eggs', models.PositiveIntegerField(default=0, help_text='Eggs not fitting in full trays')),
                ('rejected_eggs', models.PositiveIntegerField(default=0, help_text='Eggs not fit for sale')),
                ('stock_manager_confirmed', models.BooleanField(default=False)),
                ('stock_manager_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chicken_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.chickenhouse')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_eggs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_egg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_contact', models.CharField(blank=True, max_length=20)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacks_purchased', models.PositiveIntegerField()),
                ('price_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacks_in_stock', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.foodtype')),
            ],
            options={
                'verbose_name_plural': 'Food Inventories',
            },
        ),
        migrations.CreateModel(
            name='FoodDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacks_distributed', models.PositiveIntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('worker_confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('chicken_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.chickenhouse')),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributed_food', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_food', to=settings.AUTH_USER_MODEL)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('doctor_confirmed', models.BooleanField(default=False)),
                ('worker_confirmed', models.BooleanField(default=False)),
                ('purpose', models.TextField(blank=True)),
                ('chicken_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.chickenhouse')),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributed_medicine', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.medicine')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_medicine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.medicine')),
            ],
            options={
                'verbose_name_plural': 'Medicine Inventories',
            },
        ),
        migrations.CreateModel(
            name='MedicinePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.medicine')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
