# Generated by Django 5.1.7 on 2025-06-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
