# Generated by Django 5.1.7 on 2025-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_MANAGER', 'Stock Manager'), ('WORKER', 'Worker'), ('DOCTOR', 'Doctor'), ('SALES_MANAGER', 'Sales Manager')], max_length=20),
        ),
    ]
