# Generated by Django 5.1.6 on 2025-05-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('egg', 'Egg'), ('product', 'Product')], default='product', max_length=20)),
                ('good_eggs', models.PositiveIntegerField(default=0)),
                ('good_trays', models.PositiveIntegerField(default=0, editable=False)),
                ('good_loose', models.PositiveIntegerField(default=0, editable=False)),
                ('broken_eggs', models.PositiveIntegerField(default=0)),
                ('cracked_eggs', models.PositiveIntegerField(default=0)),
                ('dirty_eggs', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('egg', 'Egg'), ('tray', 'Tray'), ('crate', 'Crate'), ('kg', 'Kilogram'), ('liter', 'Liter')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('eggs_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_entries', to='poutryapp.eggscollection')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poutryapp.product')),
                ('quality_checker', models.ForeignKey(limit_choices_to={'role__in': ['worker', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Inventory',
                'verbose_name_plural': 'Store Inventory',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
