# Generated by Django 5.1.6 on 2025-05-26 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0002_store_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenhouse',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Assign a worker to this chicken house', limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicken_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
