# Generated by Django 5.1.7 on 2025-06-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chickendeathrecord',
            old_name='doctor_notes',
            new_name='notes',
        ),
    ]
