# Generated by Django 5.1.7 on 2025-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
