# Generated by Django 5.1.7 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0003_alter_eggsale_price_per_egg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenhouse',
            name='age_in_weeks',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
