# Generated by Django 5.1.7 on 2025-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0003_rename_doctor_notes_chickendeathrecord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickendeathrecord',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
    ]
