# Generated by Django 5.1.7 on 2025-06-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0004_chickendeathrecord_doctor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poutryapp.medicine'),
        ),
    ]
