# Generated by Django 5.1.6 on 2025-05-27 20:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0004_alter_order_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-date_recorded'], 'verbose_name': 'Inventory Record', 'verbose_name_plural': 'Inventory Records'},
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='store',
            name='unit',
            field=models.CharField(choices=[('number', 'Number'), ('egg', 'Egg'), ('tray', 'Tray (36 eggs)'), ('crate', 'Crate'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('box', 'Box'), ('pack', 'Pack')], default='number', max_length=10),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['entry_type'], name='poutryapp_s_entry_t_28b0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['product'], name='poutryapp_s_product_050c19_idx'),
        ),
    ]
