# Generated by Django 5.1.7 on 2025-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0004_alter_chickenhouse_age_in_weeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggsale',
            old_name='confirm_received',
            new_name='confirmed_by_sales',
        ),
        migrations.RenameField(
            model_name='eggsale',
            old_name='confirm_sales',
            new_name='confirmed_by_stock',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='rejected_eggs',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='remained_eggs',
        ),
        migrations.AddField(
            model_name='eggsale',
            name='egg_type',
            field=models.CharField(choices=[('good', 'Good Eggs'), ('rejected', 'Rejected Eggs')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='is_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='loss_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
