# Generated by Django 5.1.7 on 2025-06-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0005_alter_medicineinventory_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenhouse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicken_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
