# Generated by Django 5.2.1 on 2025-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0005_rename_confirm_received_eggsale_confirmed_by_sales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggsale',
            old_name='confirmed_by_sales',
            new_name='confirm_received',
        ),
        migrations.RenameField(
            model_name='eggsale',
            old_name='confirmed_by_stock',
            new_name='confirm_sales',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='egg_type',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='is_loss',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='loss_amount',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='loss_description',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='notes',
        ),
        migrations.AddField(
            model_name='eggsale',
            name='rejected_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='remained_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
