# Generated by Django 5.1.7 on 2025-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0006_chickenhouse_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chicken_house',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_MANAGER', 'Stock Manager'), ('WORKER', 'Worker'), ('DOCTOR', 'Doctor'), ('SALES_MANAGER', 'Doctor')], max_length=20),
        ),
    ]
