# Generated by Django 5.2.1 on 2025-06-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0006_chickenhouse_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chicken_house',
        ),
        migrations.AddField(
            model_name='eggsale',
            name='confirm_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='confirm_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='rejected_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='remained_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK_MANAGER', 'Stock Manager'), ('WORKER', 'Worker'), ('DOCTOR', 'Doctor'), ('SALES_MANAGER', 'Doctor')], max_length=20),
        ),
    ]
