# Generated by Django 5.1.7 on 2025-07-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0006_rename_confirmed_by_sales_eggsale_confirm_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=2, default=316.66, max_digits=10),
        ),
    ]
