# Generated by Django 5.1.7 on 2025-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0007_alter_eggsale_buyer_name_alter_eggsale_price_per_egg'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsale',
            name='sale_short',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='short_reason',
            field=models.TextField(default='no reason'),
        ),
    ]
