# Generated by Django 5.1.7 on 2025-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0007_remove_user_chicken_house_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsale',
            name='confirm_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='rejected_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='remained_eggs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
