# Generated by Django 5.1.7 on 2025-07-05 20:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0008_eggsale_sale_short_eggsale_short_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsale',
            name='reject_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=7, default=Decimal('316.33333299999998189377947710454463958740234375'), max_digits=10),
        ),
    ]
