# Generated by Django 5.1.7 on 2025-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0008_expensecategory_expense_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddistribution',
            name='sacks_distributed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
