# Generated by Django 5.1.7 on 2025-07-05 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0008_eggsale_sale_short_eggsale_short_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=9, default=Decimal('316.66666666600002599807339720427989959716796875'), max_digits=12),
        ),
    ]
