# Generated by Django 5.1.7 on 2025-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0008_eggsale_confirm_sales_eggsale_rejected_eggs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsale',
            name='confirm_received',
            field=models.BooleanField(default=False),
        ),
    ]
