# Generated by Django 5.1.7 on 2025-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0009_eggsale_reject_price_alter_eggsale_price_per_egg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='price_per_egg',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
