# Generated by Django 5.1.7 on 2025-07-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0010_alter_eggsale_price_per_egg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggsale',
            old_name='confirm_received',
            new_name='confirmed',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='confirm_sales',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='eggsale',
            name='remained_eggs',
        ),
        migrations.AddField(
            model_name='eggsale',
            name='sales_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='sale_short',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='short_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EggDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_received', to=settings.AUTH_USER_MODEL)),
                ('stock_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eggsale',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='poutryapp.eggdistribution'),
        ),
        migrations.CreateModel(
            name='SalesManagerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_eggs', models.PositiveIntegerField(default=0)),
                ('sold_eggs', models.PositiveIntegerField(default=0)),
                ('sales_manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
