# Generated by Django 5.1.7 on 2025-06-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0010_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenhouse',
            name='age_in_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chickenhouse',
            name='average_weight',
            field=models.FloatField(default=0.0, help_text='Average weight per chicken in kg'),
        ),
    ]
