# Generated by Django 5.1.7 on 2025-07-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poutryapp', '0011_rename_confirm_received_eggsale_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='poutryapp.eggdistribution'),
        ),
    ]
